# Generated by Django 5.0.4 on 2024-09-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='url', upload_to='estates/')),
                ('img2', models.ImageField(default='url', upload_to='estates/')),
                ('img3', models.ImageField(default='url', upload_to='estates/')),
                ('img4', models.ImageField(default='url', upload_to='estates/')),
                ('title', models.CharField(max_length=22)),
                ('description', models.CharField(default='A very good house', max_length=50)),
                ('area', models.CharField(max_length=22)),
                ('inspection_fee', models.IntegerField(default=5000)),
                ('agent_fee', models.IntegerField(default=10000)),
                ('rental_fee', models.IntegerField(default=100000)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2200)),
            ],
        ),
    ]
