# Generated by Django 3.2.8 on 2024-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
