# Generated by Django 3.2.8 on 2023-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='classes',
        ),
        migrations.AddField(
            model_name='client',
            name='applications',
            field=models.ManyToManyField(related_name='applications', to='browser.Estate'),
        ),
    ]
