# Generated by Django 3.2.8 on 2024-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_auto_20231208_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
