# Generated by Django 3.2.8 on 2024-04-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_alter_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
